

package userdashboard;

import config.config;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;


public class userdashboard extends javax.swing.JFrame {

    public userdashboard() {
        initComponents();
        displayUser(); 
    }

    void displayUser() {

    DefaultTableModel model = new DefaultTableModel();
    model.setRowCount(0);

    // ✅ Table columns (add status)
    model.setColumnIdentifiers(new String[]{
    
        "Full Name",
        "Username",
        "Email",
        "Phone",
        "Role",
        "Status"
    });

    try {
        Connection con = config.getConnection();
        String sql = "SELECT * FROM user";
        PreparedStatement ps = con.prepareStatement(sql);
        ResultSet rs = ps.executeQuery();

        while (rs.next()) {
            String status = rs.getString("status");

            // Optional: normalize text
            status = status == null ? "inactive" : status.toUpperCase();

            model.addRow(new Object[]{
               
                rs.getString("fullname"),
                rs.getString("username"),
                rs.getString("email"),
                rs.getString("phonenumber"),
                rs.getString("role"),
                status
            });
        }

        userTable.setModel(model);

        rs.close();
        ps.close();
        con.close();

    } catch (Exception e) {
        System.out.println("Error loading users: " + e.getMessage());
    }
}
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Pet = new javax.swing.JButton();
        Service = new javax.swing.JButton();
        Plot = new javax.swing.JButton();
        Home = new javax.swing.JButton();
        Users = new javax.swing.JButton();
        Settings = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ADD = new javax.swing.JButton();
        UPDATE1 = new javax.swing.JButton();
        DELETE = new javax.swing.JButton();
        SEARCHBAR = new javax.swing.JTextField();
        SEARCH = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 51, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small logo.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 90));

        Pet.setBackground(new java.awt.Color(102, 51, 0));
        Pet.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        Pet.setForeground(new java.awt.Color(255, 255, 255));
        Pet.setText("PET");
        jPanel2.add(Pet, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 210, 50));

        Service.setBackground(new java.awt.Color(102, 51, 0));
        Service.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        Service.setForeground(new java.awt.Color(255, 255, 255));
        Service.setText("SERVICE");
        jPanel2.add(Service, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 210, 50));

        Plot.setBackground(new java.awt.Color(102, 51, 0));
        Plot.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        Plot.setForeground(new java.awt.Color(255, 255, 255));
        Plot.setText("PLOT");
        jPanel2.add(Plot, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 210, 50));

        Home.setBackground(new java.awt.Color(102, 51, 0));
        Home.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        Home.setForeground(new java.awt.Color(255, 255, 255));
        Home.setText("HOME");
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });
        jPanel2.add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 210, 50));

        Users.setBackground(new java.awt.Color(102, 51, 0));
        Users.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Users.setForeground(new java.awt.Color(255, 255, 255));
        Users.setText("USERS");
        Users.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsersActionPerformed(evt);
            }
        });
        jPanel2.add(Users, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 210, 50));

        Settings.setBackground(new java.awt.Color(102, 51, 0));
        Settings.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        Settings.setForeground(new java.awt.Color(255, 255, 255));
        Settings.setText("SETTINGS");
        jPanel2.add(Settings, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 210, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 720));

        jPanel4.setBackground(new java.awt.Color(102, 51, 0));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("USERS");
        jLabel1.setToolTipText("");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, 320, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 170));

        ADD.setBackground(new java.awt.Color(102, 51, 0));
        ADD.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        ADD.setForeground(new java.awt.Color(255, 255, 255));
        ADD.setText("ADD");
        ADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADDActionPerformed(evt);
            }
        });
        jPanel1.add(ADD, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 130, 40));

        UPDATE1.setBackground(new java.awt.Color(102, 51, 0));
        UPDATE1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        UPDATE1.setForeground(new java.awt.Color(255, 255, 255));
        UPDATE1.setText("UPDATE");
        UPDATE1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UPDATE1ActionPerformed(evt);
            }
        });
        jPanel1.add(UPDATE1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 130, 40));

        DELETE.setBackground(new java.awt.Color(102, 51, 0));
        DELETE.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        DELETE.setForeground(new java.awt.Color(255, 255, 255));
        DELETE.setText("DELETE");
        DELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DELETEActionPerformed(evt);
            }
        });
        jPanel1.add(DELETE, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, 120, 40));
        jPanel1.add(SEARCHBAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 180, 260, 40));

        SEARCH.setBackground(new java.awt.Color(102, 51, 0));
        SEARCH.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        SEARCH.setForeground(new java.awt.Color(255, 255, 255));
        SEARCH.setText("SEARCH");
        SEARCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SEARCHActionPerformed(evt);
            }
        });
        jPanel1.add(SEARCH, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 180, 150, 40));

        userTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(userTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 830, 480));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ADDActionPerformed

    private void UPDATE1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UPDATE1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UPDATE1ActionPerformed

    private void SEARCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SEARCHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SEARCHActionPerformed

    private void DELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DELETEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DELETEActionPerformed

    private void UsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsersActionPerformed
        jScrollPane1.setVisible(true); // ✅ show table
    displayUser();               
    }//GEN-LAST:event_UsersActionPerformed

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        jScrollPane1.setVisible(false);
    }//GEN-LAST:event_HomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userdashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userdashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userdashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userdashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userdashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADD;
    private javax.swing.JButton DELETE;
    private javax.swing.JButton Home;
    private javax.swing.JButton Pet;
    private javax.swing.JButton Plot;
    private javax.swing.JButton SEARCH;
    private javax.swing.JTextField SEARCHBAR;
    private javax.swing.JButton Service;
    private javax.swing.JButton Settings;
    private javax.swing.JButton UPDATE1;
    private javax.swing.JButton Users;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable userTable;
    // End of variables declaration//GEN-END:variables

    
}
